name: Build
on:
  push:
    branches:
      - master # or the name of your main branch
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # node and tests with jest
      - name: node js
        uses: actions/setup-node@v1
      - run: npm ci
      - run: npm test

      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: 6de2e4b1c997716300c1f74d7f6b8cfc3cedf5f3
          SONAR_HOST_URL: https://d2bc-95-217-100-63.ngrok.io

#sonar-scanner \
#  -Dsonar.projectKey=gedgsetgsdeg \
#  -Dsonar.sources=. \
#  -Dsonar.host.url=https://d2bc-95-217-100-63.ngrok.io \
#  -Dsonar.login=6de2e4b1c997716300c1f74d7f6b8cfc3cedf5f3